-- =============================================================================
-- ClickGas - initial schema (customer app now, driver app later)
--
-- Run once in Supabase Dashboard -> SQL Editor (or `supabase db push`).
--
-- Design:
--   * profiles  : one row per auth user (customer / driver / admin), created by
--                 a trigger on sign-up. Role is never taken from the client.
--   * drivers   : extra data + live location for driver accounts (driver app).
--   * orders    : prices are recomputed server-side on insert; status changes
--                 only through the RPC functions below (no direct UPDATE).
--   * order_events : audit trail of every status change.
--   * Row Level Security on every table; helper functions are SECURITY DEFINER
--     so policies never recurse into each other.
-- =============================================================================

-- ---------------------------------------------------------------- types
create type public.user_role as enum ('customer', 'driver', 'admin');
create type public.order_status as enum ('pending', 'accepted', 'on_the_way', 'delivered', 'cancelled');
create type public.payment_method as enum ('cash', 'card');

-- ---------------------------------------------------------------- helpers
create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at := now();
  return new;
end $$;

-- ---------------------------------------------------------------- cities
create table public.cities (
  id smallint generated by default as identity primary key,
  name_ar text not null,
  name_en text not null,
  lat double precision not null,
  lng double precision not null,
  is_active boolean not null default true,
  sort_order smallint not null default 0
);

insert into public.cities (name_ar, name_en, lat, lng, sort_order) values
  ('عمّان',    'Amman',   31.9539, 35.9106, 1),
  ('الزرقاء',  'Zarqa',   32.0728, 36.0880, 2),
  ('إربد',     'Irbid',   32.5556, 35.8500, 3),
  ('الرصيفة',  'Russeifa', 32.0178, 36.0464, 4),
  ('السلط',    'Salt',    32.0392, 35.7272, 5),
  ('مادبا',    'Madaba',  31.7160, 35.7939, 6),
  ('المفرق',   'Mafraq',  32.3406, 36.2080, 7),
  ('جرش',      'Jerash',  32.2808, 35.8993, 8),
  ('عجلون',    'Ajloun',  32.3326, 35.7517, 9),
  ('الكرك',    'Karak',   31.1853, 35.7048, 10),
  ('الطفيلة',  'Tafilah', 30.8375, 35.6042, 11),
  ('معان',     'Ma''an',  30.1962, 35.7341, 12),
  ('العقبة',   'Aqaba',   29.5321, 35.0063, 13);

-- ---------------------------------------------------------------- services
create table public.services (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name_ar text not null,
  name_en text not null,
  description_ar text,
  description_en text,
  price numeric(10, 2) not null check (price >= 0),
  icon text not null default 'exchange',
  badge text,
  is_active boolean not null default true,
  sort_order smallint not null default 0,
  created_at timestamptz not null default now()
);

insert into public.services (code, name_ar, name_en, description_ar, description_en, price, icon, badge, sort_order) values
  ('exchange', 'استبدال جرة غاز', 'Cylinder exchange',
   'تبديل جرة فارغة بواحدة مليئة', 'Swap your empty cylinder for a full one',
   7.00, 'exchange', null, 1),
  ('new_cylinder', 'شراء جرة جديدة', 'New cylinder',
   'أسطوانة حديد جديدة مع الغاز', 'A brand-new steel cylinder, filled with gas',
   40.00, 'new', 'NEW', 2);

-- ---------------------------------------------------------------- app config (single row)
create table public.app_config (
  id boolean primary key default true check (id),
  delivery_fee numeric(10, 2) not null default 0,
  max_quantity smallint not null default 5,
  search_radius_km numeric(5, 2) not null default 5,
  support_phone text,
  updated_at timestamptz not null default now()
);
insert into public.app_config default values;

-- ---------------------------------------------------------------- profiles
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role public.user_role not null default 'customer',
  full_name text not null check (char_length(full_name) between 2 and 80),
  -- Jordanian mobile numbers in E.164: +9627[7|8|9]XXXXXXX
  phone text not null unique check (phone ~ '^\+9627[789][0-9]{7}$'),
  email text,
  city_id smallint references public.cities (id),
  avatar_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger profiles_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();

-- Sign-up creates the profile from the metadata sent by the app.
-- Everyone starts as a customer; drivers are promoted by an admin.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, full_name, phone, email, city_id, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.raw_user_meta_data ->> 'phone',
    new.email,
    nullif(new.raw_user_meta_data ->> 'city_id', '')::smallint,
    'customer'
  );
  return new;
end $$;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------- drivers
create table public.drivers (
  id uuid primary key references public.profiles (id) on delete cascade,
  vehicle_plate text,
  vehicle_model text,
  wallet_number text,
  city_id smallint references public.cities (id),
  is_verified boolean not null default false,
  is_online boolean not null default false,
  lat double precision,
  lng double precision,
  heading real,
  location_updated_at timestamptz,
  rating_sum integer not null default 0,
  rating_count integer not null default 0,
  current_order_id uuid,
  created_at timestamptz not null default now()
);

create index drivers_online_idx on public.drivers (is_online) where is_online;

-- ---------------------------------------------------------------- orders
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated always as identity (start with 1001) unique,
  customer_id uuid not null references public.profiles (id) on delete restrict,
  driver_id uuid references public.drivers (id) on delete set null,
  service_id smallint not null references public.services (id),
  -- snapshot of the service at order time (filled by trigger)
  service_code text not null,
  service_name_ar text not null,
  service_name_en text not null,
  quantity smallint not null default 1 check (quantity between 1 and 10),
  unit_price numeric(10, 2) not null,
  delivery_fee numeric(10, 2) not null default 0,
  total_price numeric(10, 2) not null,
  payment_method public.payment_method not null default 'cash',
  status public.order_status not null default 'pending',
  delivery_lat double precision not null,
  delivery_lng double precision not null,
  delivery_address text,
  notes text check (char_length(notes) <= 300),
  city_id smallint references public.cities (id),
  rating smallint check (rating between 1 and 5),
  rating_comment text check (char_length(rating_comment) <= 300),
  cancel_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  accepted_at timestamptz,
  on_the_way_at timestamptz,
  delivered_at timestamptz,
  cancelled_at timestamptz
);

create index orders_customer_idx on public.orders (customer_id, created_at desc);
create index orders_driver_idx on public.orders (driver_id, created_at desc);
create index orders_open_idx on public.orders (status) where status in ('pending', 'accepted', 'on_the_way');
-- A customer can have only one open order at a time.
create unique index orders_one_open_per_customer on public.orders (customer_id)
  where status in ('pending', 'accepted', 'on_the_way');

alter table public.drivers
  add constraint drivers_current_order_fk foreign key (current_order_id)
  references public.orders (id) on delete set null;

create trigger orders_updated_at before update on public.orders
  for each row execute function public.set_updated_at();

-- Prices and status are always decided by the server, never by the client.
create or replace function public.prepare_new_order()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  s public.services;
  fee numeric(10, 2);
begin
  select * into s from public.services where id = new.service_id and is_active;
  if not found then
    raise exception 'SERVICE_UNAVAILABLE';
  end if;
  select delivery_fee into fee from public.app_config where id;
  fee := coalesce(fee, 0);

  new.service_code := s.code;
  new.service_name_ar := s.name_ar;
  new.service_name_en := s.name_en;
  new.unit_price := s.price;
  new.delivery_fee := fee;
  new.total_price := s.price * new.quantity + fee;
  new.status := 'pending';
  new.driver_id := null;
  new.rating := null;
  new.rating_comment := null;
  new.cancel_reason := null;
  new.created_at := now();
  new.updated_at := now();
  new.accepted_at := null;
  new.on_the_way_at := null;
  new.delivered_at := null;
  new.cancelled_at := null;
  if new.city_id is null then
    select city_id into new.city_id from public.profiles where id = new.customer_id;
  end if;
  return new;
end $$;

create trigger orders_prepare before insert on public.orders
  for each row execute function public.prepare_new_order();

-- ---------------------------------------------------------------- order events (audit trail)
create table public.order_events (
  id bigint generated always as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  status public.order_status not null,
  actor_id uuid,
  created_at timestamptz not null default now()
);
create index order_events_order_idx on public.order_events (order_id, created_at);

create or replace function public.log_order_event()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into public.order_events (order_id, status, actor_id)
    values (new.id, new.status, auth.uid());
  end if;
  return new;
end $$;

create trigger orders_log_event after insert or update of status on public.orders
  for each row execute function public.log_order_event();

-- ---------------------------------------------------------------- RLS helper functions
-- SECURITY DEFINER so policies can check other tables without recursion.
create or replace function public.is_active_customer()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'customer' and is_active
  );
$$;

create or replace function public.is_verified_driver()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.drivers d join public.profiles p on p.id = d.id
    where d.id = auth.uid() and d.is_verified and p.is_active
  );
$$;

create or replace function public.is_my_assigned_driver(p_driver_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.orders
    where customer_id = auth.uid() and driver_id = p_driver_id
      and status in ('accepted', 'on_the_way')
  );
$$;

create or replace function public.can_view_order(p_order_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.orders
    where id = p_order_id and (customer_id = auth.uid() or driver_id = auth.uid())
  );
$$;

-- ---------------------------------------------------------------- row level security
alter table public.cities enable row level security;
alter table public.services enable row level security;
alter table public.app_config enable row level security;
alter table public.profiles enable row level security;
alter table public.drivers enable row level security;
alter table public.orders enable row level security;
alter table public.order_events enable row level security;

-- Catalog: readable before sign-in (the sign-up screen lists cities).
create policy "cities are public" on public.cities
  for select to anon, authenticated using (is_active);
create policy "services are public" on public.services
  for select to anon, authenticated using (is_active);
create policy "config is public" on public.app_config
  for select to anon, authenticated using (true);

-- Profiles: each user sees and edits only their own record.
create policy "read own profile" on public.profiles
  for select to authenticated using (id = auth.uid());
create policy "update own profile" on public.profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
revoke insert, update, delete on public.profiles from anon, authenticated;
grant update (full_name, phone, city_id, avatar_url) on public.profiles to authenticated;

-- Drivers: customers see online verified distributors on the map and the
-- driver assigned to their open order; drivers manage their own row.
create policy "online drivers are visible" on public.drivers
  for select to authenticated using (is_online and is_verified);
create policy "assigned driver is visible" on public.drivers
  for select to authenticated using (public.is_my_assigned_driver(id));
create policy "driver reads self" on public.drivers
  for select to authenticated using (id = auth.uid());
create policy "driver updates self" on public.drivers
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
revoke insert, update, delete on public.drivers from anon, authenticated;
grant update (is_online, lat, lng, heading, location_updated_at,
              vehicle_plate, vehicle_model, wallet_number) on public.drivers to authenticated;

-- Orders: customers create and read their own; drivers read pending orders
-- and the ones assigned to them. Every status change goes through an RPC.
create policy "customer reads own orders" on public.orders
  for select to authenticated using (customer_id = auth.uid());
create policy "driver reads assigned orders" on public.orders
  for select to authenticated using (driver_id = auth.uid());
create policy "verified drivers read pending orders" on public.orders
  for select to authenticated using (status = 'pending' and public.is_verified_driver());
create policy "customer creates order" on public.orders
  for insert to authenticated
  with check (customer_id = auth.uid() and public.is_active_customer());
revoke update, delete on public.orders from anon, authenticated;
revoke insert on public.orders from anon;

create policy "order parties read events" on public.order_events
  for select to authenticated using (public.can_view_order(order_id));
revoke insert, update, delete on public.order_events from anon, authenticated;

-- ---------------------------------------------------------------- RPC: auth helpers
-- Login by phone: returns the account email so the app can sign in with
-- email + password (Supabase phone login would require SMS).
create or replace function public.email_for_phone(p_phone text)
returns text language sql stable security definer set search_path = '' as $$
  select email from public.profiles where phone = p_phone and is_active limit 1;
$$;

create or replace function public.is_phone_registered(p_phone text)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.profiles where phone = p_phone);
$$;

-- ---------------------------------------------------------------- RPC: customer actions
create or replace function public.cancel_order(p_order_id uuid, p_reason text default null)
returns public.orders language plpgsql security definer set search_path = '' as $$
declare
  o public.orders;
begin
  update public.orders
     set status = 'cancelled', cancelled_at = now(), cancel_reason = left(p_reason, 200)
   where id = p_order_id and customer_id = auth.uid() and status = 'pending'
  returning * into o;
  if not found then
    raise exception 'ORDER_NOT_CANCELLABLE';
  end if;
  return o;
end $$;

create or replace function public.rate_order(p_order_id uuid, p_rating smallint, p_comment text default null)
returns public.orders language plpgsql security definer set search_path = '' as $$
declare
  o public.orders;
begin
  if p_rating < 1 or p_rating > 5 then
    raise exception 'INVALID_RATING';
  end if;
  update public.orders
     set rating = p_rating, rating_comment = left(p_comment, 300)
   where id = p_order_id and customer_id = auth.uid()
     and status = 'delivered' and rating is null
  returning * into o;
  if not found then
    raise exception 'ORDER_NOT_RATEABLE';
  end if;
  if o.driver_id is not null then
    update public.drivers
       set rating_sum = rating_sum + p_rating, rating_count = rating_count + 1
     where id = o.driver_id;
  end if;
  return o;
end $$;

-- Driver card for the customer's open order (name + phone are private
-- otherwise, so they are exposed only through this function).
create or replace function public.get_order_driver(p_order_id uuid)
returns table (
  id uuid, full_name text, phone text, vehicle_plate text, vehicle_model text,
  rating_avg numeric, lat double precision, lng double precision, heading real
) language sql stable security definer set search_path = '' as $$
  select d.id, p.full_name, p.phone, d.vehicle_plate, d.vehicle_model,
         case when d.rating_count = 0 then 0
              else round(d.rating_sum::numeric / d.rating_count, 1) end,
         d.lat, d.lng, d.heading
    from public.orders o
    join public.drivers d on d.id = o.driver_id
    join public.profiles p on p.id = d.id
   where o.id = p_order_id and o.customer_id = auth.uid();
$$;

-- ---------------------------------------------------------------- RPC: driver actions (driver app)
create or replace function public.accept_order(p_order_id uuid)
returns public.orders language plpgsql security definer set search_path = '' as $$
declare
  o public.orders;
begin
  if not public.is_verified_driver() then
    raise exception 'NOT_A_VERIFIED_DRIVER';
  end if;
  if exists (select 1 from public.orders
             where driver_id = auth.uid() and status in ('accepted', 'on_the_way')) then
    raise exception 'DRIVER_BUSY';
  end if;
  update public.orders
     set status = 'accepted', driver_id = auth.uid(), accepted_at = now()
   where id = p_order_id and status = 'pending'
  returning * into o;
  if not found then
    raise exception 'ORDER_NOT_AVAILABLE';
  end if;
  update public.drivers set current_order_id = o.id where id = auth.uid();
  return o;
end $$;

create or replace function public.start_delivery(p_order_id uuid)
returns public.orders language plpgsql security definer set search_path = '' as $$
declare
  o public.orders;
begin
  update public.orders
     set status = 'on_the_way', on_the_way_at = now()
   where id = p_order_id and driver_id = auth.uid() and status = 'accepted'
  returning * into o;
  if not found then
    raise exception 'INVALID_TRANSITION';
  end if;
  return o;
end $$;

create or replace function public.complete_order(p_order_id uuid)
returns public.orders language plpgsql security definer set search_path = '' as $$
declare
  o public.orders;
begin
  update public.orders
     set status = 'delivered', delivered_at = now()
   where id = p_order_id and driver_id = auth.uid() and status in ('accepted', 'on_the_way')
  returning * into o;
  if not found then
    raise exception 'INVALID_TRANSITION';
  end if;
  update public.drivers set current_order_id = null where id = auth.uid();
  return o;
end $$;

-- ---------------------------------------------------------------- function privileges
revoke execute on function public.email_for_phone(text) from public;
revoke execute on function public.is_phone_registered(text) from public;
grant execute on function public.email_for_phone(text) to anon, authenticated;
grant execute on function public.is_phone_registered(text) to anon, authenticated;

revoke execute on function public.cancel_order(uuid, text) from public, anon;
revoke execute on function public.rate_order(uuid, smallint, text) from public, anon;
revoke execute on function public.get_order_driver(uuid) from public, anon;
revoke execute on function public.accept_order(uuid) from public, anon;
revoke execute on function public.start_delivery(uuid) from public, anon;
revoke execute on function public.complete_order(uuid) from public, anon;
grant execute on function public.cancel_order(uuid, text) to authenticated;
grant execute on function public.rate_order(uuid, smallint, text) to authenticated;
grant execute on function public.get_order_driver(uuid) to authenticated;
grant execute on function public.accept_order(uuid) to authenticated;
grant execute on function public.start_delivery(uuid) to authenticated;
grant execute on function public.complete_order(uuid) to authenticated;

-- ---------------------------------------------------------------- realtime
alter publication supabase_realtime add table public.orders, public.drivers;
